# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  enabled: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**\*.Tests.csproj'
    arguments: '/p:CollectCoverage=true'
  enabled: true